name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "We do not accept PRs here. Please make the PR on the [main repo](https://github.com/n0bodysec/docker-images/). Thanks."
