name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    if: "! contains(github.event.head_commit.message, 'skip-ci')"
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: stremio/
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          tags: n0bodysec/stremio:latest
